# Copyright (c) 2015 The Robigalia Project Developers
# TBD: Google copyright
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT
# or http://opensource.org/licenses/MIT>, at your option. All files in the
# project carrying such notice may not be copied, modified, or distributed
# except according to those terms.
[package]
name = "sel4-sys"
version = "0.1.0"
edition = "2021"
authors = ["Corey Richardson <corey@octayn.net>", "Sam Leffler <sleffler@google.com>"]
description = "Rust interface to the seL4 kernel"
documentation = "fixme"
repository = "fixme"
readme = "README.md"
license = "MIT/Apache-2.0"
build = "build.rs"

# NB: the sel4-config crate sync's features to a kernel build by
#   parsing build artifacts (see the crate).
[build-dependencies]
sel4-config = { path = "../sel4-config" }

# Beware CONFIG_KERNEL_MCS & CONFIG_SMP_SUPPORT must match the kernel
# config for syscall numbering (aka invocation labeling) to line up.
# Other syscalls api's are generated only when the associated config
# knobs are set but do not affect the syscall ABI (e.g. CONFIG_PRINTING).
[features]
default = ["arch_generic", "serde_support"]
arch_generic = []
serde_support = ["serde"]
CONFIG_KERNEL_MCS = []
CONFIG_PRINTING = []
CONFIG_DEBUG_BUILD = []
CONFIG_SMP_SUPPORT = []
CONFIG_DANGEROUS_CODE_INJECTION = []
CONFIG_ENABLE_BENCHMARKS = []
CONFIG_BENCHMARK_TRACK_UTILISATION = []
# TCBSetBreakpoint, TCBUnsetBreakpoint, TCBSetTLSBase
CONFIG_HARDWARE_DEBUG_API = []
CONFIG_SET_TLS_BASE_SELF = []
CONFIG_VTX = []
CONFIG_HAVE_FPU = []
CONFIG_ARM_SMMU = []
CONFIG_ARM_HYPERVISOR_SUPPORT = []
CONFIG_ARM_HYP_ENABLE_VCPU_CP14_SAVE_AND_RESTORE = []

[lib]
path = "lib.rs"

[dependencies]
cfg-if = "1.0"
static_assertions = "1.1"
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
