[package]
name = "allocator"
version = "0.1.0"
authors = ["Sam Leffler <sleffler@google.com>"]
edition = "2021"

[dependencies]
cstr_core = { version = "0.2.3", default-features = false }
linked_list_allocator = { version = "0.10.4", default-features = false, features = ["const_mut_refs"] }
spin = "0.9"
