[package]
name = "reg_constants"
version = "0.1.0"
edition = "2021"

[build-dependencies]
regtool = { path = "../../../../../../../../../hw/opentitan-upstream/util/regtool" }

[features]
default = ["springbok_support"]
springbok_support = []
CONFIG_PLAT_SPARROW = []

[dependencies]
