[package]
name = "reg_constants"
version = "0.1.0"
edition = "2021"

[features]
CONFIG_PLAT_SPARROW = []

[build-dependencies]
regtool = { path = "../../../../../../../../../hw/opentitan-upstream/util/regtool" }

[dependencies]
