[package]
name = "camkes"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
sel4-config = { path = "../sel4-config" }

[features]
default = []
CONFIG_PRINTING = []
libc_compat = []

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
allocator = { path = "../allocator" }
cstr_core = { version = "0.2.3", default-features = false }
cty = "0.2.1"
logger = { path = "../logger" }
num_enum = { version = ">=0.6.1", default-features = false }
paste  = "1.0"
printf-compat = { version = "0.1.1", default-features = false }
sel4-sys = { path = "../sel4-sys" }
slot-allocator = { path = "../slot-allocator" }
spin = "0.9"
static_assertions = "1.1"
