#ifndef __CAMKES_BINDINGS_H__
#define __CAMKES_BINDINGS_H__

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually.
 */

#define CAP_RELEASE 2147483648

#endif /* __CAMKES_BINDINGS_H__ */
