#ifndef __MEMORY_MANAGER_BINDINGS_H__
#define __MEMORY_MANAGER_BINDINGS_H__

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include "CamkesBindings.h"

#define RAW_OBJ_DESC_DATA_SIZE 2048

#define RAW_MEMORY_STATS_DATA_SIZE 100

typedef enum MemoryManagerError {
  MmeSuccess = 0,
  MmeObjCountInvalid,
  MmeObjTypeInvalid,
  MmeObjCapInvalid,
  MmeCapAllocFailed,
  MmeSerializeFailed,
  MmeDeserializeFailed,
  MmeUnknownError,
  MmeAllocFailed,
  MmeFreeFailed,
} MemoryManagerError;

typedef uint8_t RawMemoryStatsData[RAW_MEMORY_STATS_DATA_SIZE];

typedef struct MemoryManagerStats {
  uintptr_t allocated_bytes;
  uintptr_t free_bytes;
  uintptr_t total_requested_bytes;
  uintptr_t overhead_bytes;
  uintptr_t allocated_objs;
  uintptr_t total_requested_objs;
  uintptr_t untyped_slab_too_small;
  uintptr_t out_of_memory;
} MemoryManagerStats;

#endif /* __MEMORY_MANAGER_BINDINGS_H__ */
