#ifndef __ML_COORDINATOR_BINDINGS_H__
#define __ML_COORDINATOR_BINDINGS_H__

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include "CamkesBindings.h"

/**
 * Errors that can occur when interacting with the MlCoordinator.
 */
typedef enum MlCoordError {
  MlCoordOk,
  InvalidModelId,
  InvalidBundleId,
  LoadModelFailed,
  NoModelSlotsLeft,
  NoSuchModel,
} MlCoordError;

#endif /* __ML_COORDINATOR_BINDINGS_H__ */
