#ifndef __PROCESS_MANAGER_BINDINGS_H__
#define __PROCESS_MANAGER_BINDINGS_H__

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#define DEFAULT_BUNDLES_CAPACITY 10

#define DEFAULT_BUNDLE_ID_CAPACITY 64

#define RAW_BUNDLE_ID_DATA_SIZE 100

typedef enum ProcessManagerError {
  Success = 0,
  BundleNotFound,
  BundleFound,
  NoSpace,
  InstallFailed,
  UninstallFailed,
  StartFailed,
  StopFailed,
  BundleIdInvalid,
  BundleDataInvalid,
} ProcessManagerError;

typedef struct Bundle {
  uint8_t data[128];
} Bundle;

typedef struct RawBundleIdData {
  uint8_t data[RAW_BUNDLE_ID_DATA_SIZE];
} RawBundleIdData;

#endif /* __PROCESS_MANAGER_BINDINGS_H__ */
