#ifndef __SECURITY_COORDINATOR_BINDINGS_H__
#define __SECURITY_COORDINATOR_BINDINGS_H__

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#define SECURITY_REPLY_DATA_SIZE 2048

typedef enum SecurityRequest {
  SrEcho = 0,
  SrInstall,
  SrUninstall,
  SrSizeBuffer,
  SrGetManifest,
  SrLoadApplication,
  SrLoadModel,
  SrReadKey,
  SrWriteKey,
  SrDeleteKey,
} SecurityRequest;

typedef enum SecurityRequestError {
  SreSuccess = 0,
  SreBundleIdInvalid,
  SreBundleDataInvalid,
  SreBundleNotFound,
  SreDeleteFirst,
  SreKeyNotFound,
  SrePackageBufferLenInvalid,
  SreValueInvalid,
  SreKeyInvalid,
  SreDeserializeFailed,
  SreSerializeFailed,
  SreCapAllocFailed,
  SreCapMoveFailed,
  SreObjCapInvalid,
  SreEchoFailed,
  SreInstallFailed,
  SreUninstallFailed,
  SreSizeBufferFailed,
  SreGetManifestFailed,
  SreLoadApplicationFailed,
  SreLoadModelFailed,
  SreReadFailed,
  SreWriteFailed,
  SreDeleteFailed,
} SecurityRequestError;

typedef uint8_t SecurityReplyData[SECURITY_REPLY_DATA_SIZE];

#endif /* __SECURITY_COORDINATOR_BINDINGS_H__ */
