#ifndef __TIMER_SERVICE_BINDINGS_H__
#define __TIMER_SERVICE_BINDINGS_H__

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

typedef enum TimerServiceError {
  TimerOk = 0,
  NoSuchTimer,
  TimerAlreadyExists,
} TimerServiceError;

typedef uintptr_t TimerId;

#endif /* __TIMER_SERVICE_BINDINGS_H__ */
